VCS: support for multi volume, added Template, added example Mount

diff --git a/scripts/VCS/DRBDConfigure/monitor b/scripts/VCS/DRBDConfigure/monitor
--- a/scripts/VCS/DRBDConfigure/monitor
+++ b/scripts/VCS/DRBDConfigure/monitor
@@ -1,42 +1,21 @@
 #!/bin/sh
-# FileOnOff Monitor script
-# Expects Resource Name
+# DRBDConfigure monitor entry point
+# Expects DRBD Resource Name in ResName attribute
 #
+# License: GPL-2.0
 # Copyright (C) 2017 LINBIT HA-Solutions GmbH
 # Roland Kammerer <roland.kammerer@linbit.com>
+# Lars Ellenberg <lars.ellenberg@linbit.com>
 ###
 
-. ${VCS_HOME}/bin/drbd_inc.sh
-RESNAME=$1; shift;
-. $VCS_HOME/bin/ag_i18n_inc.sh
+LINBITvcsag_bin=/opt/LINBITvcsag/bin
+drbd_inc=$LINBITvcsag_bin/drbd_inc.sh
 
-VCSAG_SET_ENVS $RESNAME
+. $drbd_inc || { >&2 echo "$0: Failed to source $drbd_inc"; exit 1; }
 
-VCSAG_GET_ATTR_VALUE "ResName" -1 1 "$@"
-DRBDRESNAME=${VCSAG_ATTR_VALUE}
+drbd_resource_state=$( ${DRBDSETUP} events2 --now "${DRBDRESNAME}" )
+VCSAG_LOGDBG_MSG 3 "drbd_resource_state: $drbd_resource_state"
 
-ST=$( ${DRBDADM} cstate "${DRBDRESNAME}" )
-CS=${ST%/*}
-case $CS in
-	Connected)
-		ST=$( ${DRBDADM} dstate "${DRBDRESNAME}" )
-		DS=${ST%/*}
-		case $DS in
-			UpToDate)
-				exit 110 # perfect situation
-				;;
-			Inconsistent)
-				if [ -n "$( ${DRBDSETUP} events2 --now "${DRBDRESNAME}" | grep "peer-device.*name:${DRBDRESNAME}.*replication:SyncTarget.*")" ]; then
-					exit 101 # connected + SyncTarget, so can become Primary
-				fi
-				exit 100 # offline
-				;;
-			*)
-				exit 100 # offline
-				;;
-		esac
-		;;
-	*)
-		exit 100 # offline
-		;;
-esac
+confidence_from_drbd_state "$drbd_resource_state"
+confidence=$?
+exit $confidence
diff --git a/scripts/VCS/DRBDPrimary/monitor b/scripts/VCS/DRBDPrimary/monitor
--- a/scripts/VCS/DRBDPrimary/monitor
+++ b/scripts/VCS/DRBDPrimary/monitor
@@ -1,30 +1,35 @@
 #!/bin/sh
-# FileOnOff Monitor script
-# Expects Resource Name
+# DRBDPrimary monitor entry point
+# Expects DRBD Resource Name in ResName attribute
 #
+# License: GPL-2.0
 # Copyright (C) 2017 LINBIT HA-Solutions GmbH
 # Roland Kammerer <roland.kammerer@linbit.com>
+# Lars Ellenberg <lars.ellenberg@linbit.com>
 ###
 
-. ${VCS_HOME}/bin/drbd_inc.sh
-RESNAME=$1; shift;
-. $VCS_HOME/bin/ag_i18n_inc.sh
+LINBITvcsag_bin=/opt/LINBITvcsag/bin
+drbd_inc=$LINBITvcsag_bin/drbd_inc.sh
 
-VCSAG_SET_ENVS $RESNAME
+. $drbd_inc || { >&2 echo "$0: Failed to source $drbd_inc"; exit 1; }
 
-VCSAG_GET_ATTR_VALUE "ResName" -1 1 "$@"
-DRBDRESNAME=${VCSAG_ATTR_VALUE}
+drbd_resource_state=$( ${DRBDSETUP} events2 --now "${DRBDRESNAME}" )
+VCSAG_LOGDBG_MSG 3 "drbd_resource_state: $drbd_resource_state"
 
-ST=$( ${DRBDADM} role "${DRBDRESNAME}" )
-ROLE=${ST%/*}
-case $ROLE in
-	Primary)
-		exit 101 # online (101 as a start, inc confidence later)
+role_from_drbd_state "$drbd_resource_state"
+role=$?
+
+case $role in
+	$DRBD_ROLE_PRI)
+		confidence_from_drbd_state "$drbd_resource_state"
+		confidence=$?
+		exit $confidence
 		;;
-	Secondary)
-		exit 100 # offline
+	$DRBD_ROLE_SEC)
+		exit $VCSAG_RES_OFFLINE
 		;;
 	*)
-		exit 99 # unknown
+		VCSAG_LOG_MSG E "Unknown role for $DRBDRESNAME, did you forget to link with a DRBDConfigure type resource?" 0
+		exit $VCSAG_RES_OFFLINE
 		;;
 esac
diff --git a/scripts/VCS/DRBDPrimary/offline b/scripts/VCS/DRBDPrimary/offline
--- a/scripts/VCS/DRBDPrimary/offline
+++ b/scripts/VCS/DRBDPrimary/offline
@@ -1,19 +1,34 @@
 #!/bin/sh
-# FileOnOff Offline script
-# Expects Resource Name
+# DRBDPrimary offline entry point
+# Expects DRBD Resource Name in ResName attribute
 #
+# License: GPL-2.0
 # Copyright (C) 2017 LINBIT HA-Solutions GmbH
 # Roland Kammerer <roland.kammerer@linbit.com>
+# Lars Ellenberg <lars.ellenberg@linbit.com>
 ###
 
-. ${VCS_HOME}/bin/drbd_inc.sh
-RESNAME=$1; shift;
-. $VCS_HOME/bin/ag_i18n_inc.sh
+LINBITvcsag_bin=/opt/LINBITvcsag/bin
+drbd_inc=$LINBITvcsag_bin/drbd_inc.sh
 
-VCSAG_SET_ENVS $RESNAME
+. $drbd_inc || { >&2 echo "$0: Failed to source $drbd_inc"; exit 1; }
 
-VCSAG_GET_ATTR_VALUE "ResName" -1 1 "$@"
-DRBDRESNAME=${VCSAG_ATTR_VALUE}
+drbd_resource_state=$( ${DRBDSETUP} events2 --now "${DRBDRESNAME}" )
+VCSAG_LOGDBG_MSG 3 "drbd_resource_state: $drbd_resource_state"
 
-${DRBDADM} secondary "${DRBDRESNAME}"
-exit 0
+role_from_drbd_state "$drbd_resource_state"
+role=$?
+
+case $role in
+	$DRBD_ROLE_UNNKOWN)
+		VCSAG_LOGDBG_MSG 1 "apparently not even up" 0
+		;;
+	$DRBD_ROLE_SEC)
+		VCSAG_LOGDBG_MSG 1 "already secondary" 0
+		;;
+	$DRBD_ROLE_PRI)
+		VCSAG_LOGDBG_MSG 1 "trying to demote" 0
+		${DRBDADM} secondary "${DRBDRESNAME}" || exit $VCSAG_EP_FAILED
+		;;
+esac
+exit $VCSAG_EP_DONE
diff --git a/scripts/VCS/DRBDPrimary/online b/scripts/VCS/DRBDPrimary/online
--- a/scripts/VCS/DRBDPrimary/online
+++ b/scripts/VCS/DRBDPrimary/online
@@ -1,19 +1,37 @@
 #!/bin/sh
-# FileOnOff Online script
-# Expects Resource Name
+# DRBDPrimary online entry point
+# Expects DRBD Resource Name in ResName attribute
 #
+# License: GPL-2.0
 # Copyright (C) 2017 LINBIT HA-Solutions GmbH
 # Roland Kammerer <roland.kammerer@linbit.com>
+# Lars Ellenberg <lars.ellenberg@linbit.com>
 ###
 
-. ${VCS_HOME}/bin/drbd_inc.sh
-RESNAME=$1; shift;
-. $VCS_HOME/bin/ag_i18n_inc.sh
+LINBITvcsag_bin=/opt/LINBITvcsag/bin
+drbd_inc=$LINBITvcsag_bin/drbd_inc.sh
 
-VCSAG_SET_ENVS $RESNAME
+. $drbd_inc || { >&2 echo "$0: Failed to source $drbd_inc"; exit 1; }
 
-VCSAG_GET_ATTR_VALUE "ResName" -1 1 "$@"
-DRBDRESNAME=${VCSAG_ATTR_VALUE}
+drbd_resource_state=$( ${DRBDSETUP} events2 --now "${DRBDRESNAME}" )
+VCSAG_LOGDBG_MSG 3 "drbd_resource_state: $drbd_resource_state"
 
-${DRBDADM} primary "${DRBDRESNAME}"
-exit 0
+role_from_drbd_state "$drbd_resource_state"
+role=$?
+
+if [ $role = $DRBD_ROLE_PRI ] ; then
+	VCSAG_LOGDBG_MSG 1 "already primary" 0
+	exit $VCSAG_EP_DONE
+fi
+
+confidence_from_drbd_state "$drbd_resource_state"
+confidence=$?
+
+# This may become some "min confidence level required" parameter
+if [ $confidence -lt 106 ] ; then
+	VCSAG_LOG_MSG E	"Refusing to promote, local data not UpToDate, please resync first"
+	exit $VCSAG_EP_FAILED
+fi
+
+VCSAG_LOGDBG_MSG 1 "trying to promote" 0
+${DRBDADM} primary "${DRBDRESNAME}" || exit $VCSAG_EP_FAILED
